---

- name: "Install node.js 13" 
  become: true
  shell: |
     curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
     apt install -y node.js 
    
     # Use n package version manager to use node.js 13.8.0
     npm install --global n
     n 13.8.0

- name: "Install PM2 Globally" 
  npm: 
    name: pm2
    global: yes