---

- name: "Add node.js from nodesource" 
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_10.x | sudo -E bash -

- name: "Install NodeJs 10" 
  become: true
  apt: 
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally" 
  become: true
  npm: 
    name: pm2
    global: yes
    production: yes
    state: present