---

- name: "Add node.js from nodesource" 
  become: true
  shell: |
    curl --insecure -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y node.js 
    sudo npm install --global n
    sudo n 13.8.0

- name: "Install PM2 Globally" 
  npm: 
    name: pm2
    global: yes